@startuml Milestone2_UML_Class_Diagram
skinparam classFontSize 11
skinparam classBackgroundColor beige
skinparam ClassBorderColor red
skinparam ArrowColor red


package "models" <<frame>> {
    class "Answer" {
        - id: Long
        - response: Response
        - question: Long
        - content: String
        + Answer(response: Response, Long question, content: String)
        + getId(): Long
        + getResponse(): Response
        + getQuestion(): Long
        + getContent(): String
        + setId(): void
        + setResponse(): void
        + setQuestion(): void
        + setContent(): void
        + toString(): String
        + equals(o: Object): boolean
    }

    class "AppUser" {
        - id: Long
        - username: String
        - password: String
        - listSurveys: List<Survey>
        + AppUser(username: String, password: String)
        + getId(): Long
        + getUsername(): String
        + getPassword(): String
        + getListSurveys(): List<Survey>
        + setId(): void
        + setUsername(): void
        + setPassword(): void
        + setListSurveys(): void
        + addSurvey(survey: Survey): void
        + removeSurvey(surveyId: Long): boolean
        + toString(): String
        + equals(o: Object): boolean
    }

    enum "QuestionType" {
        LONG_ANSWER("Long Answer")
        RADIO_CHOICE("Radio Choice")
        RANGE("Range")
        - types: String {readonly}
        + QuestionType(type: String)
    }

    class "Question" {
        - id: Long
        - prompt: String
        - type: QuestionType
        - survey: Survey
        + Question(survey: Survey, prompt: String, type: QuestionType)
        + getId(): Long
        + getPrompt(): String
        + getType(): QuestionType
        + getSurvey(): Survey
        + setId(): void
        + setPrompt(): void
        + setType(): void
        + setSurvey(): void
        + toString(): String
        + equals(comparedQuestion: Question): boolean
        + equals(o: Object): boolean
    }

    class "LongAnswerQuestion" {
        - charLimit: Integer
        + LongAnswerQuestion()
        + LongAnswerQuestion(survey: Survey, prompt: String, charLimit: Integer)
        + getCharLimit(): Integer
        + setCharLimit(): void
        + toString(): String
        + equals(o: Object): boolean
    }

    class "RadioChoiceQuestion" {
        - choices: String[]
        + RadioChoiceQuestion()
        + RadioChoiceQuestion(survey: Survey, prompt: String, choices: String[])
        + getChoices: String[]
        + setChoices: void
        + toString(): String
        + equals(o: Object): boolean
    }

    class "RangeQuestion" {
        - lower: Integer
        - upper: Integer
        - incremental: Integer
        + RangeQuestion()
        + RangeQuestion(prompt: String, lower: Integer, upper: Integer)
        + RangeQuestion(survey: Survey, prompt: String, lower: Integer, upper: Integer, increment: Integer)
        + getLower(): Integer
        + getUpper(): Integer
        + getIncremental(): Integer
        + setLower(): void
        + setUpper(): void
        + setIncremental(): void
        + toString(): String
        + equals(o: Object): boolean
    }

    class "Response" {
        - id: Long
        - survey: Survey
        - answers: List<Answer>
        + Response(survey: Survey)
        + getId(): Long
        + getSurvey(): Survey
        + getAnswers(): List<Answer>
        + setId(): void
        + setSurvey(): void
        + setAnswers(): void
        + addAnswer(question: Long, content: String): void
        + toString(): String
        + equals(comparedResponse: Response): boolean
        + equals(o: Object): boolean
    }

    class "Survey" {
        - id: Long
        - questions: List<Question>
        - responses: List<Response>
        - closed: boolean
        - title: String
        - user: AppUser
        + Survey(user: AppUser, title: String)
        + getId(): Long
        + getQuestions(): List<Question>
        + getResponses(): List<Response>
        + isClosed(): boolean
        + getTitle(): String
        + getUser(): AppUser
        + setId(): void
        + setQuestions(): void
        + setResponses(): void
        + setClosed(): void
        + setTitle(): void
        + setUser(): void
        + addQuestion(question: Question): boolean
        + removeQuestion(questionId: long): boolean
        + addResponse(response: Response): boolean
        + removeResponse(responseId: Long): boolean
        + getResponsesForQuestion(questionId: Long): List<String>
        + toString(): String
        + equals(o: Object): boolean
    }
}



' note right of "APIController"::createSurvey
'     // returns 200 if survey created successfully
'     // otherwise look at integer responses to handle errors
' end note

' Relationship arrows
"RangeQuestion" -up-|> "Question"
"LongAnswerQuestion" -up-|> "Question"
"RadioChoiceQuestion" -up-|> "Question"

"Question" "1" *-- "QuestionType"

"Response" "0..*  " *-- "1      " "Answer"
"Survey" "0..*  " *-- "1  " "Question"
"Survey" "0..*     " *-- "1   " "Response"
"AppUser" "0..*  " *-- "1 " "Survey"
@enduml